### ISSUE TITLE
Ability to parse array from FormData

### ISSUE THREAD

**Issue by devbytyler** [rileytomasek/zodix#11]
The docs include an example on how to parse multiple SearchParams with the same name, but there doesn't appear to be support for parsing an array from formData entries with the same name.

**Comment by narutosstudent** [comment]
Parsing an array would be cool, then we should get it through `getAll` right?

**Comment by rileytomasek** [comment]
This already works :)

I'll add an example to the docs, but this test shows how it works:
https://github.com/rileytomasek/zodix/blob/master/src/parsers.test.ts#L174

**Comment by rileytomasek** [comment]
No worries. Arrays are generally problematic with `FormData` and `URLSearchParams`.

This isn't documented, but you can pass a custom parser function [as documented here for `parseQuery()`](https://github.com/rileytomasek/zodix#custom-urlsearchparams-parsing) to `parseForm()` that gives you complete control and will solve your problem.

Zodix converts `FormData` to `URLSearchParams` and then parses that, so you just need to write the custom parser for the `URLSearchParams` representation of your form. The relevant code is [here](https://github.com/rileytomasek/zodix/blob/master/src/parsers.ts#L172).
