### ISSUE TITLE
Support other runtimes

### ISSUE THREAD

**Issue by sergiodxa** [rileytomasek/zodix#2]
Right now, the package uses `@remix-run/node` to get the `LoaderArgs` type (and if you accept #1 to get the `FormData` class).

This creates a hard requirement on Node as the runtime, but a Remix app could use Cloudflare or Deno as runtimes.

You can solve this by importing from `@remix-run/server-runtime`. The `LoaderArgs` type is exported from there and re-exported from the runtime packages, and this way you avoid the dependency on a runtime.

**Comment by rileytomasek** [comment]
Yep, this wasn't intentional. Fixed with #4.
