### ISSUE TITLE
parseQuery fails in Cloudflare functions when used with a URLSearchParams

### ISSUE THREAD

**Issue by Phoenixmatrix** [rileytomasek/zodix#45]
When using parseQuery with URLSearchParams as argument, the function fails.

parseQuery takes either a URLSearchParams as argument, or a Request, and uses the output of toString.call to find which type was parsed as argument. In most runtimes, that works fine,  but it seems like a while back Cloudflare refactored their implementation of URLSearchParams to not be quite standard, and its type, when obtained from toString, is `[object Object]`, rather than `[object URLSearchParams]`
 
That leads parseQuery to try to build a URLSearchParams from another URLSearchParams, and that of course doesn't work. The bug is technically on Cloudflare's side (it should return the right thing), but it might be safer to check properties instead. Eg: if we just check if the argument has a url property, it will work with any object that has a string url property, and revert to URLSearchParams otherwise 

Alternatively check if the argument has an .entries() method, and parse the result of Object.fromEntries(...) instead of assuming URLSearchParams. A lot of options here.

**Comment by Phoenixmatrix** [comment]
Looks like it's gonna be fixed in https://github.com/cloudflare/workerd/issues/2750

**Comment by rileytomasek** [comment]
Great, I'm going to close this because it's not our job to be handling bugs in `URLSearchParams` implementations.
