### ISSUE TITLE
useActionData<typeof action> should be type safe

### ISSUE THREAD

**Issue by luisrudge** [rileytomasek/zodix#46]
I'm not a TS wizard, but zodix already has all the information about my types. we should find a way so that we can use `useActionData` in a type safe way.

The [login page](https://github.com/rileytomasek/zodix/blob/master/examples/app/routes/login.tsx) example is not good because when you add a new field, it means you have to keep the schema and json result in sync, which is just boilerplate at this point... the ideal api should be something like this:

```tsx
import { Form, useActionData } from "@remix-run/react";
import { ActionArgs, json } from "@remix-run/server-runtime";
import { z, ZodError } from "zod";
import { zx } from "../../../src";

const schema = z.object({
  email: z.string().email({ message: "Invalid email" }),
  password: z
    .string()
    .min(8, { message: "Password must be at least 8 characters" }),
});

export async function action(args: ActionArgs) {
  const result = await zx.parseFormSafe(args.request, schema);
  if (result.success) {
    return json({ success: true, emailError: null, passwordError: null });
  }
  // Get the error messages and return them to the client.
  return json({
    success: false,
    errors: result.error.flatten(),
  });
}

export default function Login() {
  const data = useActionData<typeof action>();
  if (data?.success) {
    return <h1>Success!</h1>;
  }
  return (
    <>
      <h1>Login</h1>
      <Form method="post">
        <p>
          <label>Email:</label>
          <input name="email" />
          {data?.errors?.email?.[0] && <div>{data.errors.email[0]}</div>}
        </p>
        <p>
          <label>Password:</label>
          <input type="password" name="password" />
          {data?.errors?.password?.[0] && <div>{data.errors.password[0]}</div>}
        </p>
        <button type="submit">Login</button>
      </Form>
    </>
  );
}
```

**Comment by rileytomasek** [comment]
you need to return consistent json shapes or narrow by a discriminator. this is an issue with the action's return/typing, not zodix.

**Comment by luisrudge** [comment]
@rileytomasek thanks for the quick response and sorry for opening an issue for something that is more like a discussion 😅. 

what do you mean by discriminator in this case (you can use the login page as an example)? how come parseFormSafe can infer the exact type of the response but you can't infer an error type? 
the error type will always be:

```
{
  key1: string[];
  key2: string[]
}
```

**Comment by luisrudge** [comment]
I just found out about `inferFlattenedErrors` which is exactly what I need! for those searching for the same thing:

```tsx
type ValidationErrors = z.inferFlattenedErrors<typeof schema>['fieldErrors'];
const schema = z.object({
  email: z.string().email({ message: 'Invalid email' }),
  password: z.string().min(8, { message: 'Password must be at least 8 characters' }),
});
```
<img width="848" alt="image" src="https://github.com/user-attachments/assets/421cf962-b03b-44fc-a2da-bd8dfd55ca9c">
